name: docs

on:
  push:
    branches:
      - connectorx_doc
    # we want to run this workflow only for commits that modify the docs or workflows
    paths:
    - "docs/**"
    - .github/workflows/docs.yml

jobs:

  docs_jupyterbook:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2

    - name: Intall Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-21
          components: rustfmt
          default: true
    
    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt

    - name: Build the book
      run: |
        jupyter-book build docs

    - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: test_doc # The branch the action should deploy to.
          folder: ./ # The folder the action should deploy.
  
  docs_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-21
          components: rustfmt
          default: true

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --features all

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html

  
